apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: scraping-micronaut
  name: scraping-micronaut
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scraping-micronaut
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: scraping-micronaut
    spec:
      securityContext:
         runAsUser: 1000300
      containers:
      - image: scraping:micronaut
        name: scraping-micronaut
        ports:
        - name: web
          containerPort: 8080
        imagePullPolicy: Never
        securityContext:
          allowPrivilegeEscalation: false
---
apiVersion: v1
kind: Service
metadata:
  name: scraping-micronaut
  labels:
    app: scraping-micronaut
    k8s-app: scraping-micronaut
spec:
  selector:
    app: scraping-micronaut
  ports:
    - name: web
      port: 8080
      protocol: TCP
      targetPort: web