apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: scraping-micronaut
  labels:
    release: metrics
spec:
  selector:
    matchLabels:
      app: scraping-micronaut
  endpoints:
  - port: web
    path: '/prometheus'
    interval: 10s
    honorLabels: true