apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: health-check-springboot
  name: health-check-springboot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: health-check-springboot
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: health-check-springboot
    spec:
      securityContext:
         runAsUser: 1000300
      containers:
      - env:
        - name: SPRING_DATASOURCE_PASSWORD
          value: password
        - name: SPRING_DATASOURCE_URL
          value: jdbc:postgresql://postgresdb:5432/postgres
        - name: SPRING_DATASOURCE_USERNAME
          value: postgres
        image: health-check:spring-boot
        imagePullPolicy: Never
        name: health-check-springboot
        securityContext:
          allowPrivilegeEscalation: false
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: health-check-springboot
  name: health-check-springboot
spec:
  ports:
  - protocol: TCP
    port: 8080
    nodePort: 30033
  selector:
    app: health-check-springboot
  type: NodePort