apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: health-check-quarkus
  name: health-check-quarkus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: health-check-quarkus
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: health-check-quarkus
    spec:
      securityContext:
         runAsUser: 1000300
      containers:
      - env:
        - name: QUARKUS_DATASOURCE_PASSWORD
          value: password
        - name: QUARKUS_DATASOURCE_URL
          value: jdbc:postgresql://postgresdb:5432/postgres
        - name: QUARKUS_DATASOURCE_USERNAME
          value: postgres
        image: health-check:quarkus
        imagePullPolicy: Never
        name: health-check-quarkus
        securityContext:
          allowPrivilegeEscalation: false
        livenessProbe:
          httpGet:
            path: /actuator/health/live
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /actuator/health/ready
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: health-check-quarkus
  name: health-check-quarkus
spec:
  ports:
  - protocol: TCP
    port: 8080
    nodePort: 30799
  selector:
    app: health-check-quarkus
  type: NodePort