apiVersion: v1
kind: Namespace
metadata:
  name: k8soperator
---
apiVersion: v1
kind: Pod
metadata:
  namespace: k8soperator
  name: custom-operator
spec:
  serviceAccountName: operator-service
  containers:
    - name: custom-operator
      image: k8s-operator:1.0
      imagePullPolicy: Never